name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Faz o checkout
        uses: actions/checkout@v4

      - name: Configura o java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Verificar o Lint
        run: mvn checkstyle:check

      - name: Executa os testes
        run: mvn test

      - name: Analisa a cobertura dos testes
        run: mvn jacoco:report

      - name: Build com Maven
        run: mvn -B package --file pom.xml -DskipTests

      - name: Gera o relatório de cobertura
        uses: cicirello/jacoco-badge-generator@v2
        with:
          generate-branches-badge: true
          jacoco-csv-file: target/site/jacoco/jacoco.csv

      - name: Faz o upload pra release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.TOKEN }}
          file: target
          asset_name: IMC_API.jar
          tag: ${{ github.ref }}
          overwrite: true
          body: "Arquivo jar contendo uma API de IMC"          

      # - name: Faz o upload do relatório de coberturas do JaCoCo
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: jacoco-report
      #     path: target/site/jacoco/
          

